{% set name = "agate-sql" %}
{% set version = "0.5.6" %}
{% set compress_type = "tar.gz" %}
{% set hash = "056dc9e587fbdfdf3f1c9950f4793a5ee87622c19deba31aa0a6d6681816dcde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - agate >=1.5.0
    - sqlalchemy >=1.0.8

test:
  imports:
    - agatesql

about:
  home: http://agate-sql.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: agate-sql adds SQL read/write support to agate.
  doc_url: http://agate-sql.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-sql

extra:
  recipe-maintainers:
    - pmlandwehr
