{% set name = "agate-sql" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b1b30284a573fd416759437273dcc5c81022bdf2facb24b4aa029a62afd53b0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - agate >=1.5.0
    - sqlalchemy >=1.0.8,<2

test:
  imports:
    - agatesql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://agate-sql.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: agate-sql adds SQL read/write support to agate.
  doc_url: http://agate-sql.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-sql

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
